name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_PASSWORD: rootpassword
          MYSQL_USER: user
          MYSQL_DATABASE: addresses
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Install Entity Framework Core CLI
      run: dotnet tool install --global dotnet-ef --version 7.0.0

    - name: Check EF Core CLI Version
      run: dotnet ef --version

    - name: Clean
      run: dotnet clean UserManagement/UserManagement.csproj

    - name: Restore dependencies
      run: dotnet restore UserManagement/UserManagement.csproj

    - name: Build
      run: dotnet build UserManagement/UserManagement.csproj --no-restore

    - name: Generate Migration SQL Script
      run: dotnet ef migrations script -o migration.sql --project UserManagement/UserManagement.csproj

    - name: Apply Migration Script to MySQL
      run: |
        sudo apt-get install -y mysql-client
        mysql -h127.0.0.1 -P3306 -uroot -prootpassword addresses < migration.sql

    - name: Test
      run: dotnet test UserManagement/UserManagement.csproj --no-build --verbosity normal
